### ISSUE TITLE
Failed to run plugin

### ISSUE THREAD

**Issue by AlexeyKarash** [jonathantneal/postcss-svg-fragments#9]
Hello i try to use this plugin but has some problem to run it. I work in VS 2015, after installing this plugin I got output error in Task Runner Explorer: 

```
Failed to run "_.\projectPath_\Gulpfile.js"...
cmd.exe /c gulp --tasks-simple
_.\projectPath_\node_modules\postcss-svg-fragments\index.js:22
	utf8 = true
	     ^
SyntaxError: Unexpected token =
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (_.\projectPath_\gulpfile.js:19:19)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Liftoff.handleArguments (_.\projectPath_\node_modules\gulp\bin\gulp.js:116:3)
    at Liftoff.<anonymous> (_.\projectPath_\node_modules\liftoff\index.js:198:16)
    at module.exports (_.\projectPath_\node_modules\flagged-respawn\index.js:17:3)
    at Liftoff.<anonymous> (_.\projectPath_\node_modules\liftoff\index.js:190:9)
```

This is a list of plugins I use:
```
var gulp = require('gulp');
var del = require('del');
var uglify = require('gulp-uglify');
var concat = require('gulp-concat');
var minifyCss = require("gulp-minify-css");
var cleanCSS = require("gulp-clean-css");
var jshint = require("gulp-jshint");
var rename = require("gulp-rename");
var gulpAutoprefixer = require("gulp-autoprefixer");
var autoprefixer = require("autoprefixer");
var svgmin = require("gulp-svgmin");
var Promise = require('es6-promise').polyfill();
var postcss = require("gulp-postcss");
var precss = require("precss");
var assets = require('postcss-assets');
var inlineSvg = require('postcss-inline-svg');
var postSVGO = require('postcss-svgo');
var postSVGfrag = require('postcss-svg-fragments');
var calc = require("postcss-calc");
```

**Comment by jonathantneal** [comment]
I believe this is related to https://github.com/jonathantneal/postcss-svg-fragments/issues/8

Have you considered upgrading to the LTS version of Node v6 or higher?
